#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f counter_unit.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc  --trace counter_unit.sv   --exe counter_unit_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcounter_unit.mk Vcounter_unit

# run executable simulation file
obj_dir/Vcounter_unit

#    ls /dev/tty.u*
#    /dev/tty.usbserial-110
#    /dev/ttyS3
#    chmod +x ./doit.sh